export const timeDailyInfo = [
  {
    img: "/timeTracking/icon-work.svg",
    interval: "daily",
    title: "Work",
    duration: "5hrs",
    description: "Yesterday - 7hrs",
    color: "#FF8C66",
  },
  {
    img: "/timeTracking/icon-play.svg",
    interval: "daily",
    title: "Play",
    duration: "1hr",
    description: "Yesterday - 2hrs",
    color: "#56C2E6",
  },
  {
    img: "/timeTracking/icon-study.svg",
    interval: "daily",
    title: "Study",
    duration: "0hr",
    description: "Yesterday - 1hr",
    color: "#FF5C7C",
  },
  {
    img: "/timeTracking/icon-exercise.svg",
    interval: "daily",
    title: "Exercise",
    duration: "1hr",
    description: "Yesterday - 1hr",
    color: "#4ACF81",
  },
  {
    img: "/timeTracking/icon-social.svg",
    interval: "daily",
    title: "Social",
    duration: "1hr",
    description: "Yesterday - 3hrs",
    color: "#7536D3",
  },
  {
    img: "/timeTracking/icon-self-care.svg",
    interval: "daily",
    title: "Self Care",
    duration: "0hr",
    description: "Yesterday - 1hr",
    color: "#F1C65B",
  },
];

export const timeWeeklyInfo = [
  {
    img: "/timeTracking/icon-work.svg",
    interval: "weekly",
    title: "Work",
    duration: "32hrs",
    description: "Last week - 36hrs",
    color: "#FF8C66",
  },
  {
    img: "/timeTracking/icon-play.svg",
    interval: "weekly",
    title: "Play",
    duration: "10hrs",
    description: "Last week - 8hrs",
    color: "#56C2E6",
  },
  {
    img: "/timeTracking/icon-study.svg",
    interval: "weekly",
    title: "Study",
    duration: "4hrs",
    description: "Last week - 7hrs",
    color: "#FF5C7C",
  },
  {
    img: "/timeTracking/icon-exercise.svg",
    interval: "weekly",
    title: "Exercise",
    duration: "4hrs",
    description: "Last week - 5hrs",
    color: "#4ACF81",
  },
  {
    img: "/timeTracking/icon-social.svg",
    interval: "weekly",
    title: "Social",
    duration: "5hr",
    description: "Last week - 10hrs",
    color: "#7536D3",
  },
  {
    img: "/timeTracking/icon-self-care.svg",
    interval: "weekly",
    title: "Self Care",
    duration: "7hrs",
    description: "Last week - 11hrs",
    color: "#F1C65B",
  },
];

export const timeMonthlyInfo = [
  {
    img: "/timeTracking/icon-work.svg",
    interval: "monthly",
    title: "Work",
    duration: "103hrs",
    description: "Last month - 128hrs",
    color: "#FF8C66",
  },
  {
    img: "/timeTracking/icon-play.svg",
    interval: "monthly",
    title: "Play",
    duration: "23hr",
    description: "Last month - 29hrs",
    color: "#56C2E6",
  },
  {
    img: "/timeTracking/icon-study.svg",
    interval: "monthly",
    title: "Study",
    duration: "13hrs",
    description: "Last month - 19hrs",
    color: "#FF5C7C",
  },
  {
    img: "/timeTracking/icon-exercise.svg",
    interval: "monthly",
    title: "Exercise",
    duration: "11hrs",
    description: "Last month - 18hrs",
    color: "#4ACF81",
  },
  {
    img: "/timeTracking/icon-social.svg",
    interval: "monthly",
    title: "Social",
    duration: "21hrs",
    description: "Last month - 23hrs",
    color: "#7536D3",
  },
  {
    img: "/timeTracking/icon-self-care.svg",
    interval: "monthly",
    title: "Self Care",
    duration: "7hrs",
    description: "Last month - 11hrs",
    color: "#F1C65B",
  },
];
